### ISSUE TITLE
Simplify & Optimize

### ISSUE THREAD

**Issue by bomkei** [xv-anx/dtextra#2]
README 内の画像にある以下の記述について：
```cpp
const std::vector<u32> data = {
  ...
};

memcpy(reinterpret_cast<void*>(offset), &data[0], data.size() * sizeof(u32));
```

## 1.式の簡略化

C++ らしい文法などを一切気にしないのであれば、memcpy(...) の第一引数は以下のように C のキャストで記述できます。
```cpp
(void*)offset
```

## 2. 最適化
`std::vector<...>` は動的配列ですから、`const` をつけるようであれば直接 u32 の配列を定義することを推奨します。（ --> vector クラスが持つ情報は不要）
その場合は memcpy の第２引数以降を含めて全体の書き方が変わりますので、以下に書いておきます：

（プルリクめんどくさいだけやろとか言わないで！許して！）
```
u32 const data[] = {
  ...
};

memcpy((void*)offset, data, sizeof(data));
```

**Comment by xv-anx** [comment]
ありがとうございます！参考にします！
